project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Synaptic Static"
  description: "Personal and Academic Blog of Connor Lockhart"
  site-url: https://conair94.github.io/Quarto/ # Adjust if you want this as a subfolder
  navbar:
    right:
      - text: Main Website
        href: https://conair94.github.io
      - icon: github
        href: https://github.com/conair94

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



